### ISSUE TITLE
feat(pharmacy): substitute stock selection in native Transfer Issue page

### ISSUE THREAD

**Issue by buddhika75** [hmislk/hmis#20584]
## Summary

The native Transfer Issue page (`pharmacy_transfer_issue_native.xhtml`) introduced in #20583 defers substitute stock selection.

## Background

The existing `TransferIssueForRequestsController` has `prepareSubstitute()` and `replaceSelectedSubstitute()` which allow the user to swap an unavailable item for an in-stock substitute from the same VMP group. The native SQL page does not implement this on first release (the existing Issue page still works as fallback).

## Required Work

1. Add `prepareSubstitute(TransferIssueItemRowDto)` to `TransferIssueNativeSqlController`.
2. Add substitute dialog to `pharmacy_transfer_issue_native.xhtml` matching the existing dialog pattern.
3. When a substitute is selected, update the DTO row's item, stockId, batchId, rates in-place.
4. Verify the native settle() handles the substituted item correctly (stockId changed from loaded value).

## Related

- #20583 (parent — native Transfer Issue page)
- TransferIssueForRequestsController:prepareSubstitute (lines 995–1018), replaceSelectedSubstitute (lines 1020–1071)

**Comment by buddhika75** [comment]
**Triage (2026-06-30):** Enhancement (Pharmacy) — Add substitute stock selection UI in native Transfer Issue. New feature development task.

**Comment by buddhika75** [comment]
## Feature Request 📋

Additional features for native Transfer Issue page are enhancement requests.
